### ISSUE TITLE
Seems to make is_expected *only* work with certain types of block tests

### ISSUE THREAD

**Issue by pboling** [christopheraue/ruby-rspec-is_expected_block#1]
Was that the intent?  I was hoping it would allow usage with or without.

**Comment by christopheraue** [comment]
Could you provide an example? What's the expected behavior and what do you actually get?

**Comment by pboling** [comment]
Actually I think I may have misrepresented what happened.  It failed with a particular style of block testing that I was expecting it to work with.

Take any class that has named arguments in the initializer, and then add this test, with this gem installed:
```
    context 'invalid arguments' do
      let(:arguments) { { } }
      subject { described_class.new(**arguments) }
      it "raises an error" do
        is_expected.to raise_error(ArgumentError, /missing keyword/)
      end
    end
```
It blows up.

I don't have time to make all the changes to set it up again, to see the exact error.

I don't understand your example in the readme.  Does this gem work with

**Comment by pboling** [comment]
Oh, I think I see the issue.  I need to structure the test to make the subject a callable thing.  My old implementation that I was migrating to your gem did that for me.

Nevermind.  I'll try again.
